### ISSUE TITLE
HTML template bug for JAM

### ISSUE THREAD

**Issue by atafliovich** [ProjectAT/uam#6]
HTML template shows all grades 0 for any aggregate report from jam run.

**Comment by pazz** [comment]
Hi! I've just been looking into uam for grading my intro-to-OOP first year module and I'm impressed by what I read so far. Cheers for the awesome tool!

I am having a bit of a problem with the html aggregator, and I believe it is related to this issue.
Running through the java example as documented in the jam/README, I so far had two stumbling blocks:

1. (unrelated to this issue): the `python3 test_runner.py` chokes on the first demo student (nosubmission) because the expected directory does not exists (which is to be expected) :)

2. when aggregating the results I see the following output

```
python3 templator.py aggregated.json html   
Warning: cannot generate report /home/pazz/repo/teaching/2020-COMP122-OOP/sandbox/uam/jam/examples/submissions/correct/A1/report.html. No template file.
Warning: cannot generate report /home/pazz/repo/teaching/2020-COMP122-OOP/sandbox/uam/jam/examples/submissions/failures/A1/report.html. No template file.
Warning: cannot generate report /home/pazz/repo/teaching/2020-COMP122-OOP/sandbox/uam/jam/examples/submissions/infloop/A1/report.html. No template file.
Warning: cannot generate report /home/pazz/repo/teaching/2020-COMP122-OOP/sandbox/uam/jam/examples/submissions/nosubmission/A1/report.html. No template file.
Warning: cannot generate report /home/pazz/repo/teaching/2020-COMP122-OOP/sandbox/uam/jam/examples/submissions/nullpointer/A1/report.html. No template file.
Warning: cannot generate report /home/pazz/repo/teaching/2020-COMP122-OOP/sandbox/uam/jam/examples/submissions/syntax/A1/report.html. No template file.
```

This does not look correct. More troubling, the generated global `report.html` file contains no info in individual students but still [some function code that seems to have simply been copied from the template.](https://gist.github.com/pazz/088b9535119235dd6e719bdb4cbcba61#file-report-html-L56)
Is this PHP? Do I need to view this file through some web-server that interprets this code? 
How do I use this?

Thanks!
